version: '3.4'

services:
  motiontechapi:
    image: motiontechapi:dev
    container_name: MotionTechAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MotionTechAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/mnunez/Documents/universidad/Especialidad/1 Trimestre/MotionTech/Backend/MotionTechAPI/MotionTechAPI:/app
      - /Users/mnunez/Documents/universidad/Especialidad/1 Trimestre/MotionTech/Backend/MotionTechAPI:/src
      - /Users/mnunez/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/mnunez/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/MotionTechAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true